name: base
channels:
- conda-forge
dependencies:
  - pip
  - nodejs
  - ipympl
  - python
  - numba
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn  
  - ipywidgets
  - rise
  - pip:
      - jupyter-cjk-xelatex
